name: SSH Runner

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Start tmate
        uses: mxschmitt/action-tmate@v3
        with:
          private-key: ${{ secrets.TMATE_PRIVATE_KEY }}
          
